"""create repository and document tables

Revision ID: b21b895ba1d5
Revises:
Create Date: 2026-08-09 20:59:15.421655

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b21b895ba1d5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_url", sa.String(length=500), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "default_branch",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "last_ingested_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_repositories_github_url"),
        "repositories",
        ["github_url"],
        unique=True,
    )
    op.create_index(
        op.f("ix_repositories_name"),
        "repositories",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repositories_owner"),
        "repositories",
        ["owner"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repositories_status"),
        "repositories",
        ["status"],
        unique=False,
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column(
            "document_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "path",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "title",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "source_url",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_documents_content_hash"),
        "documents",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_document_type"),
        "documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_repository_id"),
        "documents",
        ["repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_documents_repository_id"),
        table_name="documents",
    )
    op.drop_index(
        op.f("ix_documents_document_type"),
        table_name="documents",
    )
    op.drop_index(
        op.f("ix_documents_content_hash"),
        table_name="documents",
    )
    op.drop_table("documents")

    op.drop_index(
        op.f("ix_repositories_status"),
        table_name="repositories",
    )
    op.drop_index(
        op.f("ix_repositories_owner"),
        table_name="repositories",
    )
    op.drop_index(
        op.f("ix_repositories_name"),
        table_name="repositories",
    )
    op.drop_index(
        op.f("ix_repositories_github_url"),
        table_name="repositories",
    )
    op.drop_table("repositories")
    # ### end Alembic commands ###
